gamma: 0.99                       # discount factor
reward_scale: 10.0                 # scale with which to multiply rewards.
num_iter: 100
exploration_steps: 0
exploration_episodes: 10
render_train: False
render_test: False
